export const GRAFFOO_STYLES = {
    'Class': 'graphMlID=n4;shape=rect;rounded=1;arcsize=30;fillColor=#ffff00;strokeColor=#000000;strokeWidth=1.0',
    'Datatype': 'graphMlID=n6;shape=parallelogram;fillColor=#ccffcc;strokeColor=#000000;strokeWidth=1.0',
    'ClassRestriction': 'graphMlID=n5;shape=rect;rounded=1;arcsize=30;fillColor=#ffff99;strokeColor=#000000;strokeWidth=1.0;dashed=1;dashPattern=1 3',
    'instance': 'graphMlID=n9;shape=ellipse;fillColor=#ff99cc;strokeColor=#000000;strokeWidth=3.0;verticalAlign=middle;labelPosition=right;verticalLabelPosition=middle;align=left;spacingRight=1;spacing=17;',
    'predicate': 'endArrow=classic;html=1;textDirection=ltr;',
    'objectProperty': 'graphMlID=e0;rounded=0;endArrow=block;strokeColor=#000080;strokeWidth=1.0;startArrow=oval;startFill=1;endFill=1',
    'annotationPropertyFacility': 'graphMlID=e7;rounded=0;endArrow=open;strokeColor=#993300;dashed=1;dashPattern=1 1;strokeWidth=1.0;startArrow=dash;startFill=1;endFill=1;',
    'annotationProperty': 'graphMlID=e4;rounded=0;endArrow=open;strokeColor=#993300;strokeWidth=1.0;startArrow=dash;startFill=1;endFill=1',
    'objectPropertyFacility': 'graphMlID=e5;rounded=0;endArrow=block;strokeColor=#000080;dashed=1;dashPattern=1 1;strokeWidth=1.0;startArrow=oval;startFill=1;endFill=1;',
    'dataPropertyFacility': 'graphMlID=e6;rounded=0;endArrow=block;strokeColor=#008000;dashed=1;dashPattern=1 1;strokeWidth=1.0;startArrow=oval;startFill=0;endFill=0;',
    'dataProperty': 'graphMlID=e2;rounded=0;endArrow=block;strokeColor=#008000;strokeWidth=1.0;startArrow=oval;startFill=0;endFill=0',
    'datatype': 'text;html=1;spacing=0;align=left;fontFamily=dialog;fontSize=16;fontStyle=0;fontColor=#000000',
    'DatatypeRestriction': 'graphMlID=n7;shape=parallelogram;fillColor=#ecffec;strokeColor=#000000;strokeWidth=1.0;dashed=1;dashPattern=1 3',
    'ontology': 'graphMlID=n2;shape=swimlane;startSize=20;rounded=1;arcSize=5;strokeColor=#666699;strokeWidth=1.0;dashed=1;dashPattern=1 3;align=right;fillColor=#99ccff;gradientColor=none;',
    'additionalAxioms': 'shape=note;whiteSpace=wrap;html=1;backgroundOutline=1;darkOpacity=0.05;strokeColor=#A9C4EB;fillColor=#ccffff;gradientColor=none;align=left;spacingLeft=8;',
    'annotations': 'shape=note;whiteSpace=wrap;html=1;backgroundOutline=1;darkOpacity=0.05;strokeColor=#A9C4EB;fillColor=#ccffff;gradientColor=none;align=left;spacingLeft=8;',
    'SWRL': 'graphMlID=n1;shape=swimlane;startSize=20;rounded=1;arcSize=5;strokeColor=#666666;strokeWidth=1.0;dashed=1;dashPattern=5 2;fillColor=#ebebeb;fontColor=#333333;align=right;spacingRight=10;',
    'Prefixes': 'graphMlID=n0;shape=swimlane;startSize=20;fillColor=#b7b69e;strokeColor=#000000;strokeWidth=1.0;align=right;spacingRight=10;fontStyle=1',
};
